export default [
  {
    id: '0',
    name: '专利申请',
    router: '/patent-application',
    icon: 'icon-application',
    limit: '',
  },
  {
    id: '0-1',
    mpid: 'none',
    bpid: '0',
    name: '首次申请',
    router: '/first-application',
    // msg: 'todoArchive',
    limit: '',
  },
  {
    id: '1',
    name: '我的工作台',
    icon: 'icon-workbench',
    limit: '',
  },
  {
    id: '1-0',
    mpid: '1',
    bpid: '1',
    name: '我的待办',
    router: '/dashboard/todo',
    // msg: 'todoArchive',
    limit: '',
  },
  {
    id: '1-1',
    mpid: '1',
    bpid: '1',
    name: '我的专利',
    router: '/dashboard/my-patent',
    limit: '',
  },
  {
    id: '1-1-1',
    mpid: 'none',
    bpid: '1-1',
    router: '/dashboard/patent-detail',
    name: '专利详情',
  },
  {
    id: '1-2',
    mpid: '1',
    bpid: '1',
    name: '我的申请',
    router: '/patent-application/patent-view',
    limit: '',
  },
  {
    id: '1-2-1',
    mpid: 'none',
    bpid: '1-2',
    name: '申请详情',
    router: '/first-application/detail',
    limit: '',
  },
  {
    id: '1-3',
    mpid: '1',
    bpid: '1',
    name: '我的通知',
    // router: '/patent-application/patent-view',
    limit: '',
  },
  {
    id: '1-4',
    mpid: '1',
    bpid: '1',
    name: '文档导入',
    router: '/dashboard/document-import',
    limit: '',
  },

  {
    id: '6',
    name: '账单管理',
    icon: 'icon-bill',
    limit: '',
  },
  {
    id: '6-1',
    mpid: '6',
    bpid: '6',
    name: '预算执行',
    // router: '',
    limit: '',
  },
  {
    id: '6-2',
    mpid: '6',
    bpid: '6',
    name: '账单查询',
    router: '/bill-management/bill-query',
    limit: '',
  },
  {
    id: '6-3',
    mpid: '6',
    bpid: '6',
    name: '未出账单',
    router: '/bill-management/unbilled',
    limit: '',
  },
  {
    id: '6-4',
    mpid: '6',
    bpid: '6',
    name: '账单初核',
    router: '/bill-management/bill-check',
    limit: '',
  },
  {
    id: '6-5',
    mpid: '6',
    bpid: '6',
    name: '账单复核',
    router: '/bill-management/bill-review',
    limit: '',
  },
  {
    id: '6-6',
    mpid: '6',
    bpid: '6',
    name: '支付审批',
    router: '/bill-management/payment-approval',
    limit: '',
  },
  {
    id: '6-7',
    mpid: '6',
    bpid: '6',
    name: '账单凭证',
    router: '/bill-management/bill-voucher',
    limit: '',
  },
  {
    id: '6-8',
    mpid: '6',
    bpid: '6',
    name: '支付结算',
    router: '/bill-management/payment-complete',
    limit: '',
  },
  {
    id: '5',
    name: '费用管理',
    icon: 'icon-expenses',
    limit: '',
  },
  {
    id: '5-1',
    mpid: '5',
    bpid: '5',
    name: '预算管理',
    router: '/fee-management/budget-management',
    limit: '',
  },
  {
    id: '5-2',
    mpid: '5',
    bpid: '5',
    name: '费用项目',
    router: '/fee-management/cost-allocation',
    limit: '',
  },
  {
    id: '5-3',
    mpid: '5',
    bpid: '5',
    name: '代理所费用',
    router: '/fee-management/agency-fees-list',
    limit: '',
  },
  {
    id: '5-4',
    mpid: '5',
    bpid: '5',
    name: '费用环节配置',
    router: '/fee-management/process-fee',
    limit: '',
  },
  {
    id: '5-4-1',
    mpid: 'none',
    bpid: '5-4',
    name: '费用配置',
    router: '/fee-management/cost-configuration',
    limit: '',
  },

  {
    id: '2',
    name: '代理管理',
    icon: 'icon-agent',
    limit: '',
  },
  {
    id: '2-1',
    mpid: '2',
    bpid: '2',
    name: '代理人管理',
    router: '/proxy-management/agent-list',
    limit: '',
  },
  {
    id: '2-1-1',
    mpid: 'none',
    bpid: '2-1',
    name: '代理人详情',
    router: '/proxy-management/agent-detail',
  },

  {
    id: '2-2',
    mpid: '2',
    bpid: '2',
    name: '代理所管理',
    router: '/proxy-management/agency-management',
    limit: '',
  },
  {
    id: '2-2-1',
    mpid: 'none',
    bpid: '2-2',
    name: '代理所详情',
    router: '/proxy-management/agency-detail',
    limit: '',
  },
  {
    id: '2-2-2',
    mpid: 'none',
    bpid: '2-2',
    name: '添加代理所',
    router: '/proxy-management/add-agency-information',
    limit: '',
  },
  {
    id: '2-2-3',
    mpid: 'none',
    bpid: '2-2',
    name: '编辑代理所',
    router: '/proxy-management/edit-agency',
    limit: '',
  },

  {
    id: '3',
    name: '后台管理',
    icon: 'icon-backstage',
    limit: '',
  },
  {
    id: '3-6',
    mpid: '3',
    bpid: '3',
    name: '流程定义',
    router: '/backstage-management/process-view',
    limit: '',
  },
  {
    id: '3-6-1',
    mpid: 'none',
    bpid: '3-6',
    name: '流程定义配置',
    router: '/backstage-management/process-definition',
    limit: '',
  },
  {
    id: '3-7',
    mpid: '3',
    bpid: '3',
    name: '部门审核人',
    router: '/backstage-management/reviewer-list',
    limit: '',
  },
  {
    id: '3-8',
    mpid: '3',
    bpid: '3',
    name: '专利工程师',
    router: '/backstage-management/engineer-list',
    limit: '',
  },
  {
    id: '4',
    name: '企业管理',
    icon: 'icon-corp',
    limit: '',
  },
  {
    id: '4-1',
    mpid: '4',
    bpid: '4',
    name: '企业管理',
    router: '/corp-management/corp-list',
    limit: '',
  },
  {
    id: '4-1-1',
    mpid: 'none',
    bpid: '4-1',
    name: '企业详情',
    router: '/corp-management/corp-detail',
    limit: '',
  },
  {
    id: '4-2',
    mpid: '4',
    bpid: '4',
    name: '员工管理',
    router: '/corp-management/staff-list',
    limit: '',
  },
  {
    id: '4-2-1',
    mpid: 'none',
    bpid: '4-2',
    name: '员工详情',
    router: '/corp-management/staff-detail',
    limit: '',
  },
  {
    id: '4-3',
    mpid: '4',
    bpid: '4',
    name: '组织管理',
    router: '/corp-management/group-list',
    limit: '',
  },
  {
    id: '4-4',
    mpid: '4',
    bpid: '4',
    name: '角色管理',
    router: '/corp-management/role-list',
    limit: '',
  },
  {
    id: '4-5',
    mpid: '4',
    bpid: '4',
    name: '授权管理',
    router: '/corp-management/permissions-list',
    limit: '',
  },
  {
    id: '4-5-1',
    mpid: 'none',
    bpid: '4-5',
    name: '新增授权',
    router: '/corp-management/auth-add',
    limit: '',
  },

  // 预算执行
  // 账单查询
  // 未出账单
  // 账单初核
  // 账单复核
  // 账单凭证
  // 支付结项
  // {
  //   id: '6',
  //   name: '账单管理',
  //   icon: 'menu',
  //   limit: '',
  // },
  // {
  //   id: '5-1',
  //   mpid: '5',
  //   bpid: '5',
  //   name: '预算管理',
  //   router: '/fee-management/budget-management',
  //   limit: '',
  // },
  // {
  //   id: '5-16',
  //   mpid: '5',
  //   bpid: '5',
  //   name: '费用项目',
  //   router: '/backstage-management/cost-allocation',
  //   limit: '',
  // },
  // {
  //   id: '5-17',
  //   mpid: '5',
  //   bpid: '5',
  //   name: '代理所费用',
  //   router: '/backstage-management/agency-fees-list',
  //   limit: '',
  // },

  // {
  //   id: '5-19',
  //   mpid: '5',
  //   bpid: '5',
  //   name: '费用环节配置',
  //   router: '/backstage-management/process-fee',
  //   limit: '',
  // },
  // {
  //   id: '99',
  //   name: '示例',
  //   icon: 'menu',
  //   limit: '',
  // },
  // {
  //   id: '99-0',
  //   mpid: '99',
  //   bpid: '99',
  //   name: '收费规则',
  //   router: '/example/create-charge-conditions',
  //   limit: '',
  // },
  // {
  //   id: '99-0',
  //   mpid: '99',
  //   bpid: '99',
  //   name: '列表',
  //   router: '/example/list-table',
  //   limit: '',
  // },
  // {
  //   id: '99-1',
  //   mpid: '99',
  //   bpid: '99',
  //   name: '折叠面板',
  //   router: '/example/collapse',
  //   limit: '',
  // },
  // {
  //   id: '99-2',
  //   mpid: '99',
  //   bpid: '99',
  //   name: '表单详情',
  //   router: '/example/details',
  //   limit: '',
  // },
  // // {
  // //   id: '99-4',
  // //   mpid: '99',
  // //   bpid: '99',
  // //   name: '步骤',
  // //   router: '/example/process-steps',
  // //   limit: '',
  // // },
  // {
  //   id: '99-3',
  //   mpid: '99',
  //   bpid: '99',
  //   name: 'Provide-inject',
  //   router: '/example/provide-inject',
  //   limit: '',
  // },
];
